#!/bin/bash

# Usage:
#     ./checker <url> [<delay (in seconds, default: 60)>] [<action to be done at url when change is detected (default: chromium)>]
#
#     Press CTRL+C to exit infinite loop.
#
# Author: quetzelcoatlus (https://github.com/quetzelcoatlus), AD 2018

trap 'echo " Okay, I will stop. Bye :)"; exit 2' INT

if [ -z $1 ]
then
	echo "Usage: ./checker <url> [<delay (in seconds, default: 60)>] [<action to be done at url when change is detected (default: chromium)>]"
	exit 1
fi

declare -r url=${1}
declare -r delay=${2:-60}
declare -r action=${3:-chromium}

prevHTML=`curl -s -H 'Cache-Control: no-cache' ${url}`
prevHash=`echo ${prevHTML} | md5sum | awk '{printf $1}'`

while true
do
	currHTML=`curl -s -H 'Cache-Control: no-cache' ${url}`
	currHash=`echo ${currHTML} | md5sum | awk '{printf $1}'`
	if [ "${prevHash}" != "${currHash}" ]
	then
		diff <(echo "${prevHTML}") <(echo "${currHTML}")
		eval ${action} ${url}
		exit 0
	fi
	prev=${hash}
	sleep ${delay}
done
